<a href="https://colab.research.google.com/github/xhxuciedu/CS206/blob/master/qr_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.random.randn(5,5)

In [0]:
# make A symmetric
A = (A+A.T)/2

In [11]:
A

array([[-0.77833798, -0.19190322, -0.12613364, -0.01428858, -0.55974396],
       [-0.19190322,  0.73611207, -0.61334389,  0.42843068,  0.31337495],
       [-0.12613364, -0.61334389, -0.09828931, -0.9227317 , -0.18030284],
       [-0.01428858,  0.42843068, -0.9227317 , -1.1936998 ,  1.38357732],
       [-0.55974396,  0.31337495, -0.18030284,  1.38357732,  0.42065415]])

## Calculate Hessenberg form of A

In [0]:
from scipy.linalg import hessenberg

In [0]:
H, Q = hessenberg(A, calc_q=True)

In [0]:
np.set_printoptions(precision=3, suppress=True)
#np.set_printoptions(formatter={"float_kind": lambda x: "%g" % x})


In [29]:
print(H)

[[-0.778  0.605  0.     0.     0.   ]
 [ 0.605  0.52  -1.311  0.     0.   ]
 [ 0.    -1.311 -0.076  1.406 -0.   ]
 [ 0.     0.     1.406 -0.814 -0.583]
 [ 0.     0.     0.    -0.583  0.235]]


## Run QR algorithm

In [0]:
# QR algorithm
A = H
for i in range(50):
  Q,R = np.linalg.qr(A)
  A = R.dot(Q)

In [37]:
print(A)

[[-2.262  0.006 -0.    -0.    -0.   ]
 [ 0.006  1.98  -0.    -0.    -0.   ]
 [ 0.    -0.    -1.024  0.    -0.   ]
 [ 0.     0.     0.     0.545  0.   ]
 [ 0.     0.     0.    -0.    -0.153]]


In [40]:
np.linalg.eig(H)

(array([-2.262,  1.98 , -1.024, -0.153,  0.545]),
 array([[ 0.133,  0.141, -0.868, -0.418, -0.188],
        [-0.326,  0.645,  0.352, -0.431, -0.411],
        [-0.629, -0.653,  0.014, -0.414, -0.079],
        [ 0.675, -0.353,  0.319, -0.379, -0.418],
        [ 0.157,  0.118,  0.148, -0.569,  0.784]]))